spring.application.name=bookshop

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.zrbasjuykskhczdisojg
spring.datasource.password=LGMMyn7Tw0Eeq2rv
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=2
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration